Hotfix for error
Hotfix to prevent an error (and get the JSON output to the console) while using:

```
jsdoc somefile.js -t templates/haruki -d console -q format=json
```

The error received is:

```
org.mozilla.javascript.EcmaError: TypeError: Cannot find function dump in object
 [object JavaImporter].
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.jav
a:3689)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.jav
a:3667)
        at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:369
5)
        at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:37
14)
        at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.j
ava:3786)
        at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(Scr
iptRuntime.java:2268)
        at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRun
time.java:2250)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_templates_haruki_publish_js_115._c_anonymous_4(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_templates_haruki_publish_js_115.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)

        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_cli_js_21._c_anonymous_28(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_cli_js_21.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java
:85)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_cli_js_21._c_anonymous_25(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_cli_js_21.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java
:85)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_cli_js_21._c_anonymous_16(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_cli_js_21.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java
:74)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_cli_js_21._c_anonymous_10(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_cli_js_21.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)

        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_jsdoc_js_1._c_anonymous_4(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)

        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_jsdoc_js_1._c_script_0(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:3
94)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:309
0)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_jsdoc_js_1.call(Unknown Source)
        at org.mozilla.javascript.gen.file__C__Users_djthomps_Desktop_closure_sa
mple4_jsdoc_jsdoc_js_1.exec(Unknown Source)
        at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Re
quire.java:355)
        at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInter
face(Require.java:288)
        at org.mozilla.javascript.commonjs.module.Require.requireMain(Require.ja
va:137)
        at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:525)
        at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:176)
        at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:100)
        at org.mozilla.javascript.Context.call(Context.java:489)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
        at org.mozilla.javascript.tools.shell.Main.exec(Main.java:158)
        at org.mozilla.javascript.tools.shell.Main.main(Main.java:136)
undefined
```