Add git fetch to base pullpost instructions
Added `git fetch` to instructions to quell the following error the contributor will otherwise encounter:
error: the requested upstream branch 'base/master' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
...